import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Sidebar from './components/Sidebar'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ignite | bookswise',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className="flex h-screen">
          <Sidebar />
        </div>
        {children}
      </body>
    </html>
  )
}
